---
version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails server -b 0.0.0.0 -p 3000
    volumes:
    - ".:/app"
    ports:
    - 3000:3000
    stdin_open: true
    tty: true
    platform: linux/amd64
    environment:
      RAILS_ENV: production
